/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 81d9251d202a51715009a17406d5fede)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RunCoordinator" | "ApprovalSession" | "RateLimiter";
	}
	interface Env {
		ARTIFACTS_BUCKET: R2Bucket;
		NORTHBOUND_AUTH_MODE?: string;
		BILLING_SELF_SERVE_PROVIDER?: string;
		BILLING_RETURN_BASE_URL?: string;
		STRIPE_SECRET_KEY?: string;
		STRIPE_WEBHOOK_SECRET?: string;
		STRIPE_PRICE_ID_PRO_MONTHLY?: string;
		STRIPE_PRICE_ID_PRO_YEARLY?: string;
		STRIPE_CUSTOMER_PORTAL_RETURN_URL?: string;
		DB: D1Database;
		EVENT_QUEUE: Queue;
		RUN_COORDINATOR: DurableObjectNamespace<import("./src/index").RunCoordinator>;
		APPROVAL_SESSION: DurableObjectNamespace<import("./src/index").ApprovalSession>;
		RATE_LIMITER: DurableObjectNamespace<import("./src/index").RateLimiter>;
		RUN_WORKFLOW: Workflow<Parameters<import("./src/index").RunWorkflow['run']>[0]['payload']>;
	}
}
interface Env extends Cloudflare.Env {}
